name: Deploy to GitHub Pages
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: develop
    - run: npm install
    - run: npm run-script build
    - run: ls -la
    - run: ls dist
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: develop
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: npm install && npm run-script build
        CNAME: boopadee.com
